#!/usr/bin/env python3
"""GitHub publish helper for DocuMaster.

Publishes documentation files to a GitHub repository by creating a new
branch, committing files, and opening a pull request.

Usage:
    python github-publish.py --token $GITHUB_TOKEN --repo owner/repo \\
        --branch "docs/update" --file README.md --content "$(cat README.md)"

Requirements:
    pip install PyGithub
"""

import os
import sys
import time
import argparse

try:
    from github import Github, GithubException
except ImportError:
    print("ERROR: PyGithub not installed. Run: pip install PyGithub")
    sys.exit(1)


def parse_args():
    parser = argparse.ArgumentParser(description="DocuMaster GitHub Publisher")
    parser.add_argument("--token", required=True, help="GitHub personal access token")
    parser.add_argument("--repo", required=True, help="Repository: owner/repo")
    parser.add_argument("--base", default="main", help="Base branch (default: main)")
    parser.add_argument("--branch", help="Branch name (auto-generated if omitted)")
    parser.add_argument("--file", required=True, help="File path in repo (e.g. README.md)")
    parser.add_argument("--content", help="File content (reads from stdin if omitted)")
    parser.add_argument("--message", default="docs: update documentation via DocuMaster",
                        help="Commit message")
    parser.add_argument("--pr-title", help="Pull request title (auto-generated if omitted)")
    parser.add_argument("--dry-run", action="store_true", help="Preview only, no changes")
    return parser.parse_args()


def main():
    args = parse_args()

    # Read content
    content = args.content
    if not content:
        content = sys.stdin.read()

    if not content:
        print("ERROR: No content provided. Use --content or pipe to stdin.")
        sys.exit(1)

    # Branch name
    branch_name = args.branch or f"docs/update-documentation-{int(time.time())}"
    pr_title = args.pr_title or f"docs: update {args.file}"

    print(f"Repository: {args.repo}")
    print(f"Base branch: {args.base}")
    print(f"New branch: {branch_name}")
    print(f"File: {args.file}")
    print(f"File size: {len(content)} chars")
    print(f"PR title: {pr_title}")
    print(f"Mode: {'DRY RUN' if args.dry_run else 'LIVE'}")
    print()

    if args.dry_run:
        print("✅ Dry run complete. No changes made.")
        return

    # Initialize GitHub client
    g = Github(args.token)

    try:
        # Verify token
        user = g.get_user()
        print(f"Authenticated as: {user.login}")

        # Get repository
        repo = g.get_repo(args.repo)
        print(f"Repository: {repo.full_name}")

        # Get base branch SHA
        base_branch = repo.get_branch(args.base)
        base_sha = base_branch.commit.sha
        print(f"Base SHA: {base_sha[:12]}")

        # Create branch
        try:
            repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_sha)
            print(f"✅ Branch created: {branch_name}")
        except GithubException as e:
            if e.status == 422:
                print(f"⚠️  Branch '{branch_name}' already exists. Using it.")
            else:
                raise

        # Check if file exists
        try:
            existing = repo.get_contents(args.file, ref=branch_name)
            # Update existing file
            repo.update_file(
                path=args.file,
                message=args.message,
                content=content,
                sha=existing.sha,
                branch=branch_name
            )
            print(f"✅ File updated: {args.file}")
        except GithubException:
            # Create new file
            repo.create_file(
                path=args.file,
                message=args.message,
                content=content,
                branch=branch_name
            )
            print(f"✅ File created: {args.file}")

        # Check if PR already exists
        existing_prs = repo.get_pulls(state="open", head=branch_name)
        if existing_prs.totalCount > 0:
            pr = existing_prs[0]
            print(f"✅ PR already exists: {pr.html_url}")
        else:
            # Create pull request
            pr = repo.create_pull(
                title=pr_title,
                body=f"""## Summary

Automated documentation update generated by DocuMaster.

### Changes
- Updated `{args.file}` with ISO/IEC 26514:2022 compliant structure

### Review Checklist
- [ ] Installation steps are accurate
- [ ] Environment variables documented
- [ ] Code examples are tested
- [ ] Public API is fully documented
""",
                head=branch_name,
                base=args.base
            )
            print(f"✅ PR created: {pr.html_url}")

        print()
        print(f"🔗 {pr.html_url}")

    except GithubException as e:
        print(f"❌ GitHub API error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
